#!/bin/bash
#description:hadoop-datanode
#chkconfig: 235 98 98

#export JAVA_HOME=/usr/java/default
#export JRE_HOME=/usr/java/jdk1.6.0_20/jre
#export HADOOP_HOME=/application/search/hadoop-0.20.2-cdh3u4


case "$1" in
start)

      echo "Starting hadoop-datanode demon..."
      su - search -c "/application/search/hadoop-0.20.2-cdh3u4/bin/hadoop-daemon.sh start datanode" 
      ;;

stop)

      echo "Stopping hadoop-datanode daemon..."
      su - search -c "/application/search/hadoop-0.20.2-cdh3u4/bin/hadoop-daemon.sh stop datanode"
      ;;

restart)
      
      echo "Restarting hadoop-datanode daemon..."
      su - search -c "/application/search/hadoop-0.20.2-cdh3u4/bin/hadoop-daemon.sh stop datanode"
      sleep 3
      ps -ef|grep DataNode|grep -v grep >/dev/null
      if [ $? != 0 ]
      then 
          su - search -c "/application/search/hadoop-0.20.2-cdh3u4/bin/hadoop-daemon.sh start datanode"
      fi
      ;;

status)
      ps -ef|grep -i datanode|grep -v "grep" >/dev/null
      if [ $? = 0 ]
      then
                echo "hadoop-datanode daemon is running..."
      else
                echo "hadoop-datanode daemon is stopped"
      fi
      ;;

*)

      echo "Usage: $0 {start|stop|restart|status}"

      exit 1

      ;;

esac


