- name: copy hbase tar.gz
  action: copy src=../repositories/hbase/$item dest=${client_download_path}/$item owner=${hbase_user} group=${hbase_group}
  with_items:
        - ${hbase_ver}.tar.gz

- name: decompress hbase tar.gz
  action: command tar -zxvpf ${client_download_path}/${hbase_ver}.tar.gz -C ${hbase_user_home_path}

- name: clear hbase tar.gz
  action: file dest=${client_download_path}/$item state=absent
  with_items:
     - ${hbase_ver}.tar.gz

- name: chown search:search
  action: command /bin/chown -R search:search ${hbase_user_home_path}/${hbase_ver}

- name: chmod 755
  action: command /bin/chmod -R 755 ${hbase_user_home_path}/${hbase_ver}/bin
