- name: copy zookeeper tar.gz
  action: copy src=../repositories/zookeeper/$item dest=${client_download_path}/$item owner=${hbase_user} group=${hbase_group}
  with_items:
        - ${zookeeper_ver}.tar.gz

- name: decompress zookeeper tar.gz
  action: command tar -zxvpf ${client_download_path}/${zookeeper_ver}.tar.gz -C ${hbase_user_home_path}

- name: clear zookeeper tar.gz
  action: file dest=${client_download_path}/$item state=absent
  with_items:
     - ${zookeeper_ver}.tar.gz

- name: chown search:search
  action: command /bin/chown -R search:search ${hbase_user_home_path}/${zookeeper_ver}

- name: chmod 755
  action: command /bin/chmod -R 755 ${hbase_user_home_path}/${zookeeper_ver}/bin
