- name: scp jars
  action: copy src=${ansible_repertory_path}/lib/$item dest=${storm_user_home_path}/${storm_ver}/lib/$item owner=${storm_user} group=${storm_user_group}
  with_items:
    - hadoop-core-0.20.2-cdh3u4.jar
    - hbase-0.94.3.jar
    - guava-r09-jarjar.jar
    - protobuf-java-2.4.0a.jar