- name: ensure /tmp exists
  file: path=/tmp mode=0777 owner=root group=root  state=directory

- name: ensure /application/search/tmp directory exists
  action: file dest=${client_temp_path} owner=root group=root mode=0755 state=directory

- name: ensure /application/search/download directory exists
  action: file dest=${client_download_path} owner=root group=root mode=0755 state=directory

- name: ensure storm.local.dirdirectory exists
  action: file dest=${storm_local_dir} owner=${storm_user} group=${storm_user_group} mode=0755 state=directory