- name: copy storm tar.gz
  action: copy src=${ansible_repertory_path}/$item dest=${client_download_path}/$item owner=${storm_user} group=${storm_user_group}
  with_items:
    - ${storm_ver}.tar.gz

- name: decompress storm tar.gz
  action: command tar -zxvpf ${client_download_path}/${storm_ver}.tar.gz -C ${storm_user_home_path}

- name: clear storm tar.gz
  action: file dest=${client_download_path}/$item state=absent
  with_items:
    - ${storm-ver}.tar.gz

- name: chown search:search
  action: command /bin/chown -R search:search ${storm_user_home_path}/${storm_ver}

- name: chmod 755
  action: command /bin/chmod -R 755 ${storm_user_home_path}/${storm_ver}/bin