- name: start storm nimbus
  action: script ../scripts/stop_nimbus.sh
  only_if: '$is_nimbus'

- name: start storm supervisor
  action: script ../scripts/stop_supervisor.sh
  only_if: '$is_supervisor'

- name: rm hsperfdata
  action: shell rm -rf /tmp/hsperfdata_*