- name: ensure /application/search/.storm directory exists
  action: file dest=${storm_user_home_path}/.storm owner=${storm_user} group=${storm_user_group} mode=0755 state=directory

- name: sync storm conf
  action: template src=../templates/conf/$item dest=${storm_user_home_path}/.storm/$item owner=${storm_user} group=${storm_user_group}
  with_items:
    - storm.yaml