- name: copy hadoop tar.gz
  action: copy src=../repositories/hadoop/$item dest=${client_download_path}/$item owner=${hadoop_user} group=${hadoop_user_group}
  with_items:
        - ${hadoop_ver}.tar.gz

- name: decompress hadoop tar.gz
  action: command tar -zxvpf ${client_download_path}/${hadoop_ver}.tar.gz -C ${hadoop_user_home_path}

- name: clear hadoop tar.gz
  action: file dest=${client_download_path}/$item state=absent
  with_items:
     - ${hadoop_ver}.tar.gz

- name: chown search:search
  action: command /bin/chown -R search:search ${hadoop_user_home_path}/${hadoop_ver}

- name: chmod 755
  action: command /bin/chmod -R 755 ${hadoop_user_home_path}/${hadoop_ver}/bin