- name: copy storm tar.gz
  action: copy src=${ansible_repertory_path}/$item dest=${client_download_path}/$item owner=${rabbitmq_user} group=${rabbitmq_user_group}
  with_items:
    - ${rabbitmq_ver}.tar.gz

- name: decompress storm tar.gz
  action: command tar -zxvpf ${client_download_path}/${rabbitmq_ver}.tar.gz -C ${rabbitmq_user_home_path}

- name: clear storm tar.gz
  action: file dest=${client_download_path}/$item state=absent
  with_items:
    - ${rabbitmq_ver}.tar.gz

- name: chown search:search
  action: command /bin/chown -R search:search ${rabbitmq_user_home_path}/${rabbitmq_target_folder}

- name: chmod 755
  action: command /bin/chmod -R 755 ${rabbitmq_user_home_path}/${rabbitmq_target_folder}/sbin